import React, { useState, useEffect } from 'react';
import Card, { CardHeader, CardBody } from '../components/UI/Card';
import Input from '../components/UI/Input';
import Button from '../components/UI/Button';
import axios from 'axios';
import { Compass, CheckCircle, Circle, Map, Sparkles } from 'lucide-react';

const Roadmap = () => {
  const [roadmap, setRoadmap] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [targetRole, setTargetRole] = useState('');
  const [error, setError] = useState('');

  useEffect(() => {
    fetchRoadmap();
  }, []);

  const fetchRoadmap = async () => {
    try {
      const token = JSON.parse(localStorage.getItem('userInfo'))?.token;
      const { data } = await axios.get('/api/roadmap', {
        headers: { Authorization: `Bearer ${token}` }
      });
      setRoadmap(data);
    } catch (err) {
      if (err.response?.status !== 404) {
        setError('Failed to fetch roadmap.');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!targetRole) return;
    
    setGenerating(true);
    setError('');
    
    try {
      const token = JSON.parse(localStorage.getItem('userInfo'))?.token;
      const { data } = await axios.post('/api/roadmap/generate', 
        { targetRole }, 
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setRoadmap(data);
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to generate roadmap.');
    } finally {
      setGenerating(false);
    }
  };

  const toggleStep = async (stepId, currentStatus) => {
    try {
      const token = JSON.parse(localStorage.getItem('userInfo'))?.token;
      const { data } = await axios.put(`/api/roadmap/${roadmap._id}/step/${stepId}`,
        { isCompleted: !currentStatus },
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setRoadmap(data);
    } catch (err) {
      console.error(err);
    }
  };

  if (loading) {
    return <div className="flex items-center justify-center h-64 text-slate-400">Loading your roadmap...</div>;
  }

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <div>
        <h1 className="text-3xl font-bold text-white flex items-center gap-2">
          <Map size={32} className="text-primary-500" />
          AI Career Roadmap
        </h1>
        <p className="text-slate-400 mt-1">Generate a personalized learning path to reach your dream career.</p>
      </div>

      {error && (
        <div className="bg-red-900/30 text-red-400 p-4 rounded-xl text-sm">
          {error}
        </div>
      )}

      {!roadmap ? (
        <Card className="mt-8">
          <CardBody className="py-12 flex flex-col items-center text-center">
            <Compass size={64} className="text-slate-600 mb-6" />
            <h2 className="text-2xl font-bold text-white mb-2">Where do you want to go?</h2>
            <p className="text-slate-400 mb-8 max-w-md">
              Enter your target job role below. Our AI will analyze industry requirements and generate a structured 4-step learning roadmap just for you.
            </p>
            
            <form onSubmit={handleGenerate} className="w-full max-w-md space-y-4">
              <Input
                label="Target Job Role"
                placeholder="e.g. Frontend Developer, Data Scientist..."
                value={targetRole}
                onChange={(e) => setTargetRole(e.target.value)}
                required
              />
              <Button type="submit" className="w-full flex items-center justify-center gap-2" disabled={generating}>
                {generating ? 'Generating AI Roadmap...' : (
                  <>
                    <Sparkles size={18} />
                    Generate Roadmap
                  </>
                )}
              </Button>
            </form>
          </CardBody>
        </Card>
      ) : (
        <div className="space-y-6">
          <Card>
            <CardHeader className="flex justify-between items-center">
              <div>
                <h2 className="text-xl font-bold text-white">Your Path to {roadmap.targetRole}</h2>
                <p className="text-slate-400 text-sm mt-1">Generated by Gemini AI</p>
              </div>
              <Button variant="ghost" onClick={() => setRoadmap(null)}>Create New</Button>
            </CardHeader>
            <CardBody>
              <div className="relative border-l border-slate-700 ml-4 space-y-8">
                {roadmap.steps.map((step, idx) => (
                  <div key={step._id} className="relative pl-8">
                    {/* Timeline dot */}
                    <button 
                      onClick={() => toggleStep(step._id, step.isCompleted)}
                      className="absolute -left-3.5 top-1 bg-slate-900 p-0.5 rounded-full outline-none transition-transform hover:scale-110 focus:ring-2 focus:ring-primary-500"
                    >
                      {step.isCompleted ? (
                        <CheckCircle size={24} className="text-emerald-500 bg-slate-900 rounded-full" />
                      ) : (
                        <Circle size={24} className="text-slate-600 bg-slate-900 rounded-full" />
                      )}
                    </button>
                    
                    <div className={`transition-opacity ${step.isCompleted ? 'opacity-50' : 'opacity-100'}`}>
                      <h3 className={`text-lg font-bold mb-1 ${step.isCompleted ? 'text-slate-400 line-through' : 'text-white'}`}>
                        {step.title}
                      </h3>
                      <p className="text-slate-400 leading-relaxed">
                        {step.description}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </CardBody>
          </Card>
        </div>
      )}
    </div>
  );
};

export default Roadmap;
